language: python
python:
  # We don't use Travis' Python as we use Anaconda, but this keeps us organised
  - "3.6"

git:
  depth: 1

addons:
  apt:
    update: true

before_install:
  # Install Rust nightly
  - export CARGO_HOME="$HOME/cargo"
  - export RUSTUP_HOME="$HOME/rustup"
  - curl https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
  - export PATH="$CARGO_HOME/bin:$PATH"

  # Install Anaconda (https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html)
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  # Build and activate our environment
  - conda env create -f environment.lock.yml
  - source activate base36

script: pytest
