name: base36
channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- click
- cython
- dask
- distributed
- gensim
- hdfs3
- ipdb
- ipykernel
- ipython
- ipyvolume
- ipywidgets
- joblib
- jupyter
#- jupyter_contrib_nbextensions
- matplotlib
- nbconvert
- nbformat
- networkx
- nltk
- notebook
- numpy
- pandas
- pip
- progressbar2
- pydot
- pytest
- scikit-learn
- scipy
- seaborn
- spacy
- statsmodels
- tqdm
- ujson
- pip:
  - jupyterlab
  - jupyterlab-discovery
  - jupyterlab-geojson
  - jupyterlab-widgets
  - keras-tqdm
  - nbdime
  - setuptools-rust
  - "https://anaconda.org/intel/tensorflow/1.6.0/download/tensorflow-1.6.0-cp36-cp36m-linux_x86_64.whl"
  - "git+https://github.com/ixxi-dante/keras@b50534bd55151c72782ecc630e21bb2e4d9a68d7#egg=keras"
  - "git+https://github.com/ixxi-dante/jwalk@fd8d2e83cf5726dfcba96b6ff6991e4cd974d594#egg=jwalk"
  - "--editable=."

