name: base36
channels:
- conda-forge
- defaults
dependencies:
- jupyter_contrib_core=0.3.3=py36_1
- jupyter_contrib_nbextensions=0.3.3=py36_0
- jupyter_highlight_selected_word=0.1.0=py36_0
- jupyter_latex_envs=1.4.0=py36_1
- jupyter_nbextensions_configurator=0.4.0=py36_0
- libxslt=1.1.32=0
- lxml=4.1.1=py36_0
- asn1crypto=0.24.0=py36_0
- attrs=17.3.0=py36h5ab58ff_0
- bcrypt=3.1.4=py36h621fe67_0
- bleach=2.1.2=py36_0
- bokeh=0.12.13=py36h2f9c1c0_0
- boost=1.65.1=py36_4
- boost-cpp=1.65.1=h14c3975_4
- boto=2.48.0=py36h6e4cd66_1
- bz2file=0.98=py36_0
- bzip2=1.0.6=h6d464ef_2
- ca-certificates=2017.08.26=h1d4fec5_0
- certifi=2017.11.5=py36hf29ccca_0
- cffi=1.11.4=py36h9745a5d_0
- chardet=3.0.4=py36h0f667ec_1
- click=6.7=py36h5253387_0
- cloudpickle=0.5.2=py36h84cdd9c_0
- coverage=4.4.2=py36hca7c4c5_0
- cryptography=2.1.4=py36hd09be54_0
- curl=7.57.0=h84994c4_0
- cycler=0.10.0=py36h93f1223_0
- cymem=1.31.2=py36_0
- cython=0.27.3=py36h1860423_0
- cytoolz=0.8.2=py36h708bfd4_0
- dask=0.16.1=py36_0
- dask-core=0.16.1=py36_0
- dbus=1.12.2=hd3e2b69_0
- decorator=4.2.1=py36_0
- dill=0.2.7.1=py36h644ae93_0
- distributed=1.20.2=py36_0
- entrypoints=0.2.3=py36h1aec115_2
- expat=2.2.5=he0dffb1_0
- fontconfig=2.12.4=h88586e7_1
- freetype=2.8=hab7d2ae_1
- ftfy=4.4.3=py36_0
- gensim=3.1.0=py36hc2fc318_0
- glib=2.53.6=h5d9569c_2
- gmp=6.1.2=h6c8ec71_1
- gst-plugins-base=1.12.4=h33fb286_0
- gstreamer=1.12.4=hb53b477_0
- h5py=2.7.1=py36h3585f63_0
- hdf5=1.10.1=h9caa474_1
- hdfs3=0.3.0=py36_1
- heapdict=1.0.0=py36h79797d7_0
- html5lib=1.0.1=py36h2f9c1c0_0
- hypothesis=3.38.5=py36h196a6cc_0
- icu=58.2=h9c2bf20_1
- idna=2.6=py36h82fb2a8_1
- intel-openmp=2018.0.0=hc7b2577_8
- ipykernel=4.8.0=py36_0
- ipython=6.2.1=py36h88c514a_1
- ipython_genutils=0.2.0=py36hb52b0d5_0
- ipywidgets=7.1.0=py36_0
- jedi=0.11.1=py36_0
- jinja2=2.10=py36ha16c418_0
- joblib=0.11=py36_0
- jpeg=9b=h024ee3a_2
- jsonschema=2.6.0=py36h006f8b5_0
- jupyter=1.0.0=py36h9896ce5_0
- jupyter_client=5.2.1=py36_0
- jupyter_console=5.2.0=py36he59e554_1
- jupyter_core=4.4.0=py36h7c827e3_0
- jupyterlab=0.31.1=py36_0
- jupyterlab_launcher=0.10.2=py36_0
- keras=2.1.3=py36_0
- krb5=1.14.2=hcdc1b81_6
- libboost=1.65.1=habcd387_4
- libcurl=7.57.0=h1ad7b7a_0
- libedit=3.1=heed3624_0
- libffi=3.2.1=hd88cf55_4
- libgcc-ng=7.2.0=h7cc24e2_2
- libgcrypt=1.8.0=h14c3975_2
- libgfortran-ng=7.2.0=h9f7466a_2
- libgpg-error=1.27=h14c3975_2
- libgsasl=1.8.0=h14c3975_3
- libhdfs3=2.3.0=h97226ba_1
- libiconv=1.15=h63c8f33_5
- libntlm=1.4=h14c3975_2
- libpng=1.6.34=hb9fc6fc_0
- libprotobuf=3.4.1=h5b8497f_0
- libsodium=1.0.15=hf101ebd_0
- libssh2=1.8.0=h9cfc8f7_4
- libstdcxx-ng=7.2.0=h7a57d05_2
- libuuid=1.0.3=h1bed415_2
- libxcb=1.12=hcd93eb1_4
- libxml2=2.9.4=h2e8b1d7_6
- locket=0.2.0=py36h787c0ad_1
- markupsafe=1.0=py36hd9260cd_1
- matplotlib=2.1.2=py36h0e671d2_0
- mistune=0.8.3=py36_0
- mkl=2018.0.1=h19d6760_4
- msgpack-numpy=0.4.1=py36hfef8c07_0
- msgpack-python=0.5.1=py36h6bb024c_0
- murmurhash=0.28.0=py36_0
- nbconvert=5.3.1=py36hb41ffb7_0
- nbformat=4.4.0=py36h31c9010_0
- ncurses=6.0=h9df7e31_2
- networkx=2.1=py36_0
- nltk=3.2.5=py36h7532b22_0
- notebook=5.3.1=py36_0
- numpy=1.12.1=py36he24570b_1
- openssl=1.0.2n=hb7f436b_0
- pandas=0.22.0=py36hf484d3e_0
- pandoc=1.19.2.1=hea2e7c5_1
- pandocfilters=1.4.2=py36ha6701b7_1
- paramiko=2.4.0=py36hd285e23_0
- parso=0.1.1=py36h35f843b_0
- partd=0.3.8=py36h36fd896_0
- pathlib=1.0.1=py36_0
- patsy=0.5.0=py36_0
- pcre=8.41=hc27e229_1
- pexpect=4.3.1=py36_0
- pickleshare=0.7.4=py36h63277f8_0
- pip=9.0.1=py36h6c6f9ce_4
- plac=0.9.6=py36_0
- pluggy=0.6.0=py36hb689045_0
- preshed=1.0.0=py36_0
- progressbar2=3.34.3=py36h0413d66_0
- prompt_toolkit=1.0.15=py36h17d85b1_0
- protobuf=3.4.1=py36h306e679_0
- psutil=5.4.3=py36h14c3975_0
- ptyprocess=0.5.2=py36h69acd42_0
- py=1.5.2=py36h29bf505_0
- py-boost=1.65.1=py36hf484d3e_4
- pyasn1=0.4.2=py36h4d1db45_0
- pycparser=2.18=py36hf9f622e_1
- pydot=1.2.3=py36h2c9da84_0
- pygments=2.2.0=py36h0d3125c_0
- pympler=0.5=py36h6b12e4d_0
- pynacl=1.2.0=py36hb6d7a8d_0
- pyopenssl=17.5.0=py36h20ba746_0
- pyparsing=2.2.0=py36hee85983_1
- pyqt=5.6.0=py36h0386399_5
- pysocks=1.6.7=py36hd97a5b1_1
- pytest=3.3.2=py36_0
- pytest-runner=3.0=py36hd5415d6_0
- python=3.6.4=hc3d631a_1
- python-dateutil=2.6.1=py36h88d3b88_1
- python-utils=2.2.0=py36_0
- pytz=2017.3=py36h63b9c63_0
- pyyaml=3.12=py36hafb9ca4_1
- pyzmq=16.0.3=py36he2533c7_0
- qt=5.6.2=h974d657_12
- qtconsole=4.3.1=py36h8f73b5b_0
- readline=7.0=ha6073c6_4
- regex=2017.4.5=py36_0
- requests=2.18.4=py36he2e5f8d_1
- scikit-learn=0.19.1=py36h7aa7ec6_0
- scipy=1.0.0=py36hbf646e7_0
- seaborn=0.8.1=py36hfad7ec4_0
- send2trash=1.4.2=py36_0
- setuptools=38.4.0=py36_0
- simplegeneric=0.8.1=py36h2cb9092_0
- sip=4.18.1=py36h51ed4ed_2
- six=1.11.0=py36h372c433_1
- smart_open=1.5.3=py36_0
- sortedcontainers=1.5.9=py36_0
- spacy=2.0.5=py36hf484d3e_0
- sqlite=3.21.0=h1bed415_0
- statsmodels=0.8.0=py36h8533d0b_0
- tblib=1.3.2=py36h34cf8b6_0
- tensorflow=1.1.0=np112py36_0
- termcolor=1.1.0=py36_0
- terminado=0.8.1=py36_0
- testpath=0.3.1=py36h8cadb63_0
- thinc=6.10.1=py36hd61447b_0
- tk=8.6.7=hc745277_3
- toolz=0.9.0=py36_0
- tornado=4.5.3=py36_0
- tqdm=4.19.4=py36ha5a5176_0
- traitlets=4.3.2=py36h674d592_0
- ujson=1.35=py36_0
- urllib3=1.22=py36hbe7ace6_0
- wcwidth=0.1.7=py36hdf4376a_0
- webencodings=0.5.1=py36h800622e_1
- werkzeug=0.14.1=py36_0
- wheel=0.30.0=py36hfd4bba0_1
- widgetsnbextension=3.1.0=py36_0
- wrapt=1.10.11=py36h28b7045_0
- xz=5.2.3=h55aa19d_2
- yaml=0.1.7=had09818_2
- zeromq=4.2.2=hbedb6e5_2
- zict=0.1.3=py36h3a3bf81_0
- zlib=1.2.11=ha838bed_2
- zope=1.0=py36_0
- zope.interface=4.4.3=py36h0ccbf34_0
- pip:
  - graphviz==0.8.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.1
  - jupyter-console==5.2.0
  - jupyter-contrib-core==0.3.3
  - jupyter-contrib-nbextensions==0.3.3
  - jupyter-core==4.4.0
  - jupyter-highlight-selected-word==0.1.0
  - jupyter-latex-envs==1.4.0
  - jupyter-nbextensions-configurator==0.4.0
  - jupyterlab-launcher==0.10.2
  - prompt-toolkit==1.0.15
  - semantic-version==2.6.0
  - setuptools-rust==0.8.3
  - setuptools-scm==1.15.6
  - smart-open==1.5.3
  - "git+https://github.com/ixxi-dante/jwalk@fd8d2e83cf5726dfcba96b6ff6991e4cd974d594#egg=jwalk"
  - "--editable=."
prefix: /home/sl/.conda/envs/base36

