name: base36
channels:
- defaults
dependencies:
- asn1crypto=0.22.0=py36h265ca7c_1
- bleach=2.0.0=py36h688b259_0
- boto=2.48.0=py36h6e4cd66_1
- bz2file=0.98=py36_0
- ca-certificates=2017.08.26=h1d4fec5_0
- certifi=2017.7.27.1=py36h8b7b77e_0
- cffi=1.10.0=py36had8d393_1
- chardet=3.0.4=py36h0f667ec_1
- cryptography=2.0.3=py36ha225213_1
- cycler=0.10.0=py36h93f1223_0
- cymem=1.31.2=py36_0
- cython=0.26.1=py36h21c49d0_0
- cytoolz=0.8.2=py36h708bfd4_0
- dbus=1.10.22=h3b5a359_0
- decorator=4.1.2=py36hd076ac8_0
- dill=0.2.7.1=py36h644ae93_0
- entrypoints=0.2.3=py36h1aec115_2
- expat=2.2.5=he0dffb1_0
- fontconfig=2.12.4=h88586e7_1
- freetype=2.8=hab7d2ae_1
- ftfy=4.4.3=py36_0
- gensim=3.0.1=py36h4ebfbf4_0
- glib=2.53.6=h5d9569c_2
- gmp=6.1.2=h6c8ec71_1
- gst-plugins-base=1.12.2=he3457e5_0
- gstreamer=1.12.2=h4f93127_0
- html5lib=0.999999999=py36h2cfc398_0
- icu=58.2=h211956c_0
- idna=2.6=py36h82fb2a8_1
- intel-openmp=2018.0.0=h15fc484_7
- ipykernel=4.6.1=py36hbf841aa_0
- ipython=6.1.0=py36hc72a948_1
- ipython_genutils=0.2.0=py36hb52b0d5_0
- ipywidgets=7.0.0=py36h7b55c3a_0
- jedi=0.10.2=py36h552def0_0
- jinja2=2.9.6=py36h489bce4_1
- joblib=0.11=py36_0
- jpeg=9b=h024ee3a_2
- jsonschema=2.6.0=py36h006f8b5_0
- jupyter=1.0.0=py36h9896ce5_0
- jupyter_client=5.1.0=py36h614e9ea_0
- jupyter_console=5.2.0=py36he59e554_1
- jupyter_core=4.3.0=py36h357a921_0
- libedit=3.1=heed3624_0
- libffi=3.2.1=hd88cf55_4
- libgcc-ng=7.2.0=h7cc24e2_2
- libgfortran-ng=7.2.0=h9f7466a_2
- libpng=1.6.32=hda9c8bc_2
- libsodium=1.0.13=h31c71d8_2
- libstdcxx-ng=7.2.0=h7a57d05_2
- libxcb=1.12=h84ff03f_3
- libxml2=2.9.4=h6b072ca_5
- markupsafe=1.0=py36hd9260cd_1
- matplotlib=2.1.0=py36hba5de38_0
- mistune=0.8.1=py36h3d5977c_0
- mkl=2018.0.0=hb491cac_4
- murmurhash=0.26.4=py36_0
- nbconvert=5.3.1=py36hb41ffb7_0
- nbformat=4.4.0=py36h31c9010_0
- ncurses=6.0=h9df7e31_2
- networkx=2.0=py36h7e96fb8_0
- nltk=3.2.4=py36h1a0979f_0
- notebook=5.2.1=py36h690a4eb_0
- numpy=1.13.3=py36ha12f23b_0
- openssl=1.0.2m=h26d622b_1
- pandas=0.21.0=py36h78bd809_1
- pandoc=1.19.2.1=hea2e7c5_1
- pandocfilters=1.4.2=py36ha6701b7_1
- pathlib=1.0.1=py36_0
- patsy=0.4.1=py36ha3be15e_0
- pcre=8.41=hc27e229_1
- pexpect=4.2.1=py36h3b9d41b_0
- pickleshare=0.7.4=py36h63277f8_0
- pip=9.0.1=py36h6c6f9ce_4
- plac=0.9.6=py36_0
- preshed=1.0.0=py36_0
- prompt_toolkit=1.0.15=py36h17d85b1_0
- ptyprocess=0.5.2=py36h69acd42_0
- pycparser=2.18=py36hf9f622e_1
- pygments=2.2.0=py36h0d3125c_0
- pyopenssl=17.2.0=py36h5cc804b_0
- pyparsing=2.2.0=py36hee85983_1
- pyqt=5.6.0=py36h0386399_5
- pysocks=1.6.7=py36hd97a5b1_1
- python=3.6.3=h1284df2_4
- python-dateutil=2.6.1=py36h88d3b88_1
- pytz=2017.2=py36hc2ccc2a_1
- pyzmq=16.0.2=py36h3b0cf96_2
- qt=5.6.2=h974d657_12
- qtconsole=4.3.1=py36h8f73b5b_0
- readline=7.0=ha6073c6_4
- regex=2017.09.23=py36h2527052_0
- requests=2.18.4=py36he2e5f8d_1
- scikit-learn=0.19.1=py36h7aa7ec6_0
- scipy=1.0.0=py36hbf646e7_0
- seaborn=0.8.0=py36h197244f_0
- setuptools=36.5.0=py36he42e2e1_0
- simplegeneric=0.8.1=py36h2cb9092_0
- sip=4.18.1=py36h51ed4ed_2
- six=1.11.0=py36h372c433_1
- smart_open=1.5.3=py36_0
- spacy=1.9.0=py36hc78c2e1_1
- sqlite=3.20.1=hb898158_2
- statsmodels=0.8.0=py36h8533d0b_0
- termcolor=1.1.0=py36_0
- terminado=0.6=py36ha25a19f_0
- testpath=0.3.1=py36h8cadb63_0
- thinc=6.5.2=py36_0
- tk=8.6.7=hc745277_3
- toolz=0.8.2=py36h81f2dff_0
- tornado=4.5.2=py36h1283b2a_0
- tqdm=4.19.4=py36ha5a5176_0
- traitlets=4.3.2=py36h674d592_0
- ujson=1.35=py36_0
- urllib3=1.22=py36hbe7ace6_0
- wcwidth=0.1.7=py36hdf4376a_0
- webencodings=0.5.1=py36h800622e_1
- wheel=0.29.0=py36he7f4e38_1
- widgetsnbextension=3.0.2=py36hd01bb71_1
- wrapt=1.10.11=py36h28b7045_0
- xz=5.2.3=h55aa19d_2
- zeromq=4.2.2=hbedb6e5_2
- zlib=1.2.11=ha838bed_2
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - "-e git+https://github.com/ixxi-dante/jwalk@fd8d2e83cf5726dfcba96b6ff6991e4cd974d594#egg=jwalk"
  - prompt-toolkit==1.0.15
  - setuptools-scm==1.15.6
  - smart-open==1.5.3
prefix: /home/slerique/anaconda3/envs/base36

