name: base36-grunchgpu
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_0
  - attrs=17.4.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.1=openblas
  - bleach=2.1.3=py_0
  - blinker=1.4=py_0
  - bokeh=0.12.15=py36_0
  - boost-cpp=1.66.0=1
  - bzip2=1.0.6=1
  - ca-certificates=2018.1.18=0
  - certifi=2018.1.18=py36_0
  - cffi=1.11.5=py36_0
  - chardet=3.0.4=py36_0
  - click=6.7=py_1
  - cloudpickle=0.5.2=py_0
  - cryptography=2.2.1=py36_0
  - curl=7.59.0=0
  - cycler=0.10.0=py36_0
  - cymem=1.31.2=py36_0
  - cython=0.28.1=py36_0
  - cytoolz=0.8.2=py36_0
  - dask=0.17.2=py_0
  - dask-core=0.17.2=py_0
  - dbus=1.10.22=0
  - decorator=4.2.1=py36_0
  - dill=0.2.7.1=py36_0
  - distributed=1.21.5=py36_0
  - entrypoints=0.2.3=py36_1
  - expat=2.2.5=0
  - fontconfig=2.12.6=0
  - freetype=2.8.1=0
  - gensim=3.4.0=py36_0
  - gettext=0.19.8.1=0
  - glib=2.55.0=0
  - gmp=6.1.2=0
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=1
  - hdfs3=0.3.0=py36_0
  - heapdict=1.0.0=py36_0
  - html5lib=1.0.1=py_0
  - icu=58.2=0
  - idna=2.6=py36_1
  - imageio=2.3.0=py36_0
  - ipdb=0.11=py36_0
  - ipykernel=4.8.2=py36_0
  - ipython=6.3.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipyvolume=0.4.5=py36_0
  - ipywebrtc=0.3.0=py36_0
  - ipywidgets=7.2.0=py36_0
  - jedi=0.11.1=py36_0
  - jinja2=2.10=py36_0
  - joblib=0.11=py36_0
  - jpeg=9b=2
  - jsonschema=2.6.0=py36_1
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36_0
  #- jupyter_contrib_core=0.3.3=py36_1
  #- jupyter_contrib_nbextensions=0.4.0=py36_0
  - jupyter_core=4.4.0=py_0
  #- jupyter_highlight_selected_word=0.1.1=py36_0
  #- jupyter_latex_envs=1.4.4=py36_0
  #- jupyter_nbextensions_configurator=0.4.0=py36_0
  - keras=2.1.5=py36_0
  - kiwisolver=1.0.1=py36_1
  - krb5=1.14.6=0
  - libffi=3.2.1=3
  - libgcrypt=1.8.0=1
  - libgpg-error=1.27=1
  - libgsasl=1.8.0=2
  - libhdfs3=2.3=1
  - libiconv=1.15=0
  - libntlm=1.4=1
  - libpng=1.6.34=0
  - libprotobuf=3.5.2=0
  - libsodium=1.0.16=0
  - libssh2=1.8.0=2
  - libtiff=4.0.9=0
  - libuuid=1.0.3=1
  - libxcb=1.13=0
  - libxml2=2.9.8=0
  - locket=0.2.0=py36_1
  - markupsafe=1.0=py36_0
  - matplotlib=2.2.2=py36_1
  - mistune=0.8.3=py_0
  - more-itertools=4.1.0=py_0
  - msgpack-numpy=0.4.1=py_0
  - msgpack-python=0.4.8=py36_0
  - murmurhash=0.28.0=py36_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - ncurses=5.9=10
  - networkx=2.1=py36_0
  - nltk=3.2.5=py_0
  - notebook=5.4.1=py36_0
  - numpy=1.14.2=py36_blas_openblas_200
  - oauthlib=2.0.7=py_0
  - olefile=0.45.1=py36_0
  - openblas=0.2.20=7
  - openssl=1.0.2n=0
  - packaging=17.1=py_0
  - pandas=0.22.0=py36_0
  - pandoc=2.1.3=0
  - pandocfilters=1.4.1=py36_0
  - parso=0.1.1=py_0
  - partd=0.3.8=py36_0
  - patsy=0.5.0=py36_0
  - pcre=8.41=1
  - pexpect=4.4.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pillow=5.1.0=py36_0
  - pip=9.0.3=py36_0
  - plac=0.9.6=py36_0
  - pluggy=0.6.0=py_0
  - preshed=1.0.0=py36_0
  - progressbar2=3.34.3=py36_0
  - prompt_toolkit=1.0.15=py36_0
  - psutil=5.4.3=py36_0
  - ptyprocess=0.5.2=py36_0
  - py=1.5.3=py_0
  - pycparser=2.18=py36_0
  - pydot=1.2.4=py_0
  - pygments=2.2.0=py36_0
  - pyjwt=1.6.1=py_0
  - pyopenssl=17.5.0=py36_1
  - pyparsing=2.2.0=py36_0
  - pyqt=5.6.0=py36_4
  - pysocks=1.6.8=py36_1
  - pytest=3.5.0=py36_0
  - pytest-runner=4.2=py_0
  - python=3.6.5=0
  - python-crfsuite=0.9.2=py36_0
  - python-dateutil=2.7.2=py_0
  - python-utils=2.3.0=py36_0
  - pytz=2018.3=py_0
  - pywavelets=0.5.2=py36_1
  - pyyaml=3.12=py36_1
  - pyzmq=17.0.0=py36_4
  - qt=5.6.2=7
  - qtconsole=4.3.1=py36_0
  - readline=7.0=0
  - regex=2017.11.09=py36_0
  - requests=2.18.4=py36_1
  - requests-oauthlib=0.8.0=py36_1
  - scikit-image=0.13.1=py36_0
  - scikit-learn=0.19.1=py36_blas_openblas_201
  - scipy=1.0.1=py36_blas_openblas_200
  - seaborn=0.8.1=py36_0
  - send2trash=1.5.0=py_0
  - setuptools=39.0.1=py36_0
  - simplegeneric=0.8.1=py36_0
  - sip=4.18=py36_1
  - six=1.11.0=py36_1
  - smart_open=1.5.6=py36_0
  - sortedcontainers=1.5.9=py36_0
  - spacy=2.0.11=py36_0
  - sqlite=3.20.1=2
  - statsmodels=0.8.0=py36_0
  - tblib=1.3.2=py36_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36_0
  - thinc=6.10.2=py36_0
  - tk=8.6.7=0
  - toolz=0.9.0=py_0
  - tornado=5.0.1=py36_1
  - tqdm=4.20.0=py_0
  - traitlets=4.3.2=py36_0
  - traittypes=0.0.6=py36_0
  - twython=3.6.0=py36_0
  - ujson=1.35=py36_0
  - urllib3=1.22=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5=py36_0
  - wheel=0.31.0=py36_0
  - widgetsnbextension=3.2.0=py36_0
  - wrapt=1.10.11=py36_0
  - xorg-libxau=1.0.8=3
  - xorg-libxdmcp=1.1.2=3
  - xz=5.2.3=0
  - yaml=0.1.7=0
  - zeromq=4.2.5=1
  - zict=0.1.3=py_0
  - zlib=1.2.11=0
  - boto=2.48.0=py36h6e4cd66_1
  - bz2file=0.98=py36_0
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran=3.0.0=1
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - pip:
    - absl-py==0.1.13
    - astor==0.6.2
    - boto3==1.7.1
    - botocore==1.10.1
    - docutils==0.14
    - gast==0.2.0
    - grpcio==1.10.1
    - jmespath==0.9.3
    - jupyterlab==0.31.12
    - jupyterlab-discovery==4.0.0
    - jupyterlab-geojson==0.4.0
    - jupyterlab-launcher==0.10.5
    - jupyterlab-widgets==0.6.15
    - markdown==2.6.11
    - protobuf==3.5.2.post1
    - s3transfer==0.1.13
    - semantic-version==2.6.0
    - setuptools-rust==0.9.1
    - setuptools-scm==1.17.0
    - werkzeug==0.14.1
    - "wheelhouse/tensorflow-1.6.0-cp36-cp36m-linux_x86_64.whl"
    - "git+https://github.com/ixxi-dante/keras@b50534bd55151c72782ecc630e21bb2e4d9a68d7#egg=keras"
    - "git+https://github.com/ixxi-dante/jwalk@fd8d2e83cf5726dfcba96b6ff6991e4cd974d594#egg=jwalk"
    - "--editable=."
prefix: /home/sl/.conda/envs/base36-grunchgpu

