name: base36
channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- click
- cython
- dask
- distributed
- gensim
- hdfs3
- ipykernel
- ipython
- ipyvolume
- ipywidgets
- joblib
- jupyter
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- keras
- matplotlib
- nbconvert
- nbformat
- networkx
- nltk
- notebook
- numpy
- pandas
- pip
- progressbar2
- pytest
- scikit-learn
- scipy
- seaborn
- spacy
- statsmodels
- ujson
- widgetsnbextension
- pip:
  - jupyterlab
  - jupyterlab-discovery
  - jupyterlab-geojson
  - jupyterlab-widgets
  - setuptools-rust
  - "https://anaconda.org/intel/tensorflow/1.4.0/download/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl"
  - "git+https://github.com/ixxi-dante/jwalk@fd8d2e83cf5726dfcba96b6ff6991e4cd974d594#egg=jwalk"
  - "--editable=."

