[package]
name = "rust-utils"
version = "0.1.0"
authors = ["SÃ©bastien Lerique <sl@mehho.net>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.2", features = ["extension-module"] }
rayon = "0.9"
regex = "0.2"
